In [ ]:
#One Dimensional array
import numpy as np
a = np.array ([10,20,30])
print(a)

[10 20 30]


In [ ]:
#Two Dimensional Array
b = np.array([[10,20,30],[40,50,60]])
print(b)

[[10 20 30]
 [40 50 60]]


In [ ]:
import numpy as np
a = np.array ([10,20,30])
b = np.array([[10,20,30],[40,50,60]])
print(a.shape)
print(b.shape)
print(a.ndim)
print(b.ndim)
print(b.dtype)

(3,)
(2, 3)
1
2
int64


In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
x = np.array([[13,14,15],[16,17,18]])
y = np.array([[40,50,60],[98,21,34]])
print(np.dot(x, y.T))

[[2120 2078]
 [2570 2537]]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a**3)

[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[ 1  8 27]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[:6])

[1 2 3 4 5 6]


In [ ]:
c=a.reshape(4,2)
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])

np.vstack((a, b))
np.hstack((a, b))

array([[1, 2, 3, 4]])

In [ ]:
np.sum(a+b)

np.int64(10)

In [2]:
import pandas as pd
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64


In [4]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
}
df1 = pd.DataFrame(data)
print(df1)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [6]:
df = pd.read_csv('/content/students.csv')

In [7]:
df.head(2)

Name  Age  Marks
0    Ram   20     70
1  Shyam   21     80

In [10]:
df.tail(2)

Name  Age  Marks
2   Sita   22     90
3  Geeta   20     65

In [11]:
df.shape

(4, 3)

In [12]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [13]:
df.isnull()

Name    Age  Marks
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [14]:
df.isnull().sum()

Name     0
Age      0
Marks    0
dtype: int64

In [15]:
df.dropna()

Name  Age  Marks
0    Ram   20     70
1  Shyam   21     80
2   Sita   22     90
3  Geeta   20     65

In [16]:
df.loc[0]               # Row by label
df.iloc[0]

Name     Ram
Age       20
Marks     70
Name: 0, dtype: object

In [18]:
df[df['Age'] > 21]

Name  Age  Marks
2  Sita   22     90

In [21]:
df.replace(20,23)

Name  Age  Marks
0    Ram   23     70
1  Shyam   21     80
2   Sita   22     90
3  Geeta   23     65

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   Marks   4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes


In [25]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [28]:
df2 = pd.read_csv('/content/ml_pandas_practice.csv')

ID     Name   Age Gender Department JoiningDate   Salary  Rating  \
0   1    Alice  25.0      F         HR  2021-01-15  50000.0     4.5   
1   2      Bob  30.0      M         IT  2020-07-23  60000.0     3.8   
2   3  Charlie   NaN      M         IT  2022-03-01  55000.0     4.2   
3   4    David  22.0      M    Finance  2021-08-10  58000.0     3.9   
4   5      Eva  28.0      F         HR  2019-12-01      NaN     4.0   

  PromotionEligible  RemoteWorker  
0               Yes          True  
1                No         False  
2               Yes          True  
3                No         False  
4               Yes          True

In [32]:
df2.shape

(5, 10)

In [33]:
df2.columns

Index(['ID', 'Name', 'Age', 'Gender', 'Department', 'JoiningDate', 'Salary',
       'Rating', 'PromotionEligible', 'RemoteWorker'],
      dtype='object')

In [34]:
df2.interpolate()

/tmp/ipython-input-34-2041328577.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df2.interpolate()


ID     Name   Age Gender Department JoiningDate   Salary  Rating  \
0   1    Alice  25.0      F         HR  2021-01-15  50000.0     4.5   
1   2      Bob  30.0      M         IT  2020-07-23  60000.0     3.8   
2   3  Charlie  26.0      M         IT  2022-03-01  55000.0     4.2   
3   4    David  22.0      M    Finance  2021-08-10  58000.0     3.9   
4   5      Eva  28.0      F         HR  2019-12-01  58000.0     4.0   

  PromotionEligible  RemoteWorker  
0               Yes          True  
1                No         False  
2               Yes          True  
3                No         False  
4               Yes          True

In [36]:
df2.loc[2]

ID                            3
Name                    Charlie
Age                         NaN
Gender                        M
Department                   IT
JoiningDate          2022-03-01
Salary                  55000.0
Rating                      4.2
PromotionEligible           Yes
RemoteWorker               True
Name: 2, dtype: object

In [41]:
df2.index=['a','b','c','d','e']
df2

ID     Name   Age Gender Department JoiningDate   Salary  Rating  \
a   1    Alice  25.0      F         HR  2021-01-15  50000.0     4.5   
b   2      Bob  30.0      M         IT  2020-07-23  60000.0     3.8   
c   3  Charlie   NaN      M         IT  2022-03-01  55000.0     4.2   
d   4    David  22.0      M    Finance  2021-08-10  58000.0     3.9   
e   5      Eva  28.0      F         HR  2019-12-01      NaN     4.0   

  PromotionEligible  RemoteWorker  
a               Yes          True  
b                No         False  
c               Yes          True  
d                No         False  
e               Yes          True

In [43]:
df2['Age'].fillna(df2['Age'].mean(),inplace=True)
df2

ID     Name    Age Gender Department JoiningDate   Salary  Rating  \
a   1    Alice  25.00      F         HR  2021-01-15  50000.0     4.5   
b   2      Bob  30.00      M         IT  2020-07-23  60000.0     3.8   
c   3  Charlie  26.25      M         IT  2022-03-01  55000.0     4.2   
d   4    David  22.00      M    Finance  2021-08-10  58000.0     3.9   
e   5      Eva  28.00      F         HR  2019-12-01      NaN     4.0   

  PromotionEligible  RemoteWorker  
a               Yes          True  
b                No         False  
c               Yes          True  
d                No         False  
e               Yes          True

In [44]:
df2.astype({'Age':'int'})

ID     Name  Age Gender Department JoiningDate   Salary  Rating  \
a   1    Alice   25      F         HR  2021-01-15  50000.0     4.5   
b   2      Bob   30      M         IT  2020-07-23  60000.0     3.8   
c   3  Charlie   26      M         IT  2022-03-01  55000.0     4.2   
d   4    David   22      M    Finance  2021-08-10  58000.0     3.9   
e   5      Eva   28      F         HR  2019-12-01      NaN     4.0   

  PromotionEligible  RemoteWorker  
a               Yes          True  
b                No         False  
c               Yes          True  
d                No         False  
e               Yes          True